# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic (*sub-namespace, see below)
# - topic   : input topic of ackermann-msgs::AckermannDriveStamped type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

ackermann_mux:
  ros__parameters:
    use_stamped: true
    topics:
      navigation:
        topic   : nav2_ackermann_cmd
        timeout : 0.5
        priority: 10
      joystick:
        topic   : joy_ackermann_cmd
        timeout : 0.5
        priority: 100
      keyboard:
        topic   : kb_ackermann_cmd
        timeout : 0.5
        priority: 90